# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f26f7a1a1340ae763deb510d0dba2be6660ab29bd4e8b2f0f66b0518abe4655960933dc3ead8d2cd2f2d24f989a4e46399c1de4214c19ab8765c776825c4ad3b

test:
  secret_key_base: 035050b08b59708d190f458ddde3ac6b0cd4b6c8422d6f43e90cdb3804fc0ade3203fc72d7c35fcc24882314973e18a99d6ec296e4d584a54ca73e562acf2020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
